# Server ID, you can generate a new one if you want to reset the link between your Minecraft server and the discord bot.
server-id: UUID

# Websocket URL, Dont change if you dont know what you are doing!
websocket-url: "ws://james.vacso.cloud:10000"

# The room ID, this is often the same as the server ID but can be changed.
# If change you will need to update this in the bot config as well!
room-id: UUID

# API Endpoint URL, Dont change if you dont know what you are doing!
api-url: "https://api.james.vacso.cloud"

# MC Events to listen to, you can disable any of these if you want.
events:
  chat: true
  join: true
  leave: true
  death: true
  advancement: true
  server-start: true
  server-stop: true