name: EnderLink
main: com.example.enderlink.EnderLink
version: 0.4.3
api-version: 1.21
commands:
  enderlink:
    description: Main command for EnderLink plugin
    usage: /<command>
    aliases: [el]